### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by hearsilent** [laenger/ViewPagerBottomSheet#25]
```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object java.lang.ref.Reference.get()' on a null object reference
       at biz.laenger.android.vpbs.ViewPagerBottomSheetBehavior.invalidateScrollingChild(ViewPagerBottomSheetBehavior.java:432)
       at biz.laenger.android.vpbs.BottomSheetUtils$BottomSheetViewPagerListener$1.run(BottomSheetUtils.java:35)
       at android.os.Handler.handleCallback(Handler.java:789)
       at android.os.Handler.dispatchMessage(Handler.java:98)
       at android.os.Looper.loop(Looper.java:169)
       at android.app.ActivityThread.main(ActivityThread.java:6595)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
```

**Comment by hearsilent** [comment]
Deprecate #16

**Comment by jthou20121212** [comment]
same problem
